### ISSUE TITLE
Airbrake.io script is broken (maybe because of new APIs)?

### ISSUE THREAD

**Issue by ostinelli** [cppforlife/checkman#24]
The URL used to check for project errors, `http://my-project.airbrake.io/projects/{PROJET-ID}/errors.xml?auth_token={TOKEN}`, now returns a 404.

Not sure where you got the original documentation for this, but according to the [API overview](http://help.airbrake.io/kb/api-2/api-overview):

> To get the XML for the 30 most recently active errors:
> http://your_account.airbrake.io/errors.xml?auth_token=TOKEN

I don't see how to specify a specific project in this URL, but I just skimmed through the docs.

r.

**Comment by cppforlife** [comment]
Merged PR that uses v3 api.
