### ISSUE TITLE
Please remove ci.jenkins-ci.org from default checks

### ISSUE THREAD

**Issue by rtyler** [cppforlife/checkman#74]
The defaults included for checkman have been hammering the Jenkins project's Jenkins instance that I have long since inserted a custom redirect to [this page](https://jenkins.io/infra/ci-redirects/)

This traffic is abusive and fills our access logs with garbage requests. I would like to kindly ask that you remove our public Jenkins instance from the defaults for Checkman.

**Comment by daniel-beck** [comment]
FWIW https://github.com/cppforlife/checkman/blob/d2f7ad5dcab4efa44762142bdcbdb3399ca72b99/scripts/jenkins_build.check#L265 is very inefficient as well, `depth` should never be used productively. `tree` is much better.

See https://ci.jenkins.io/api/ section *Controlling the amount of data you fetch*
